### ISSUE TITLE
Tagged Docker Hub build for 1.6.2

### ISSUE THREAD

**Issue by metasim** [gitblit/gitblit-docker#3]
Would you be willing to make a tagged build on hub.docker.com for 1.6.2?

**Comment by gitblit** [comment]
Sure.  Looks like I can not tag an existing build so I have to kick-off a new build?

**Comment by metasim** [comment]
Good question, for which I'm not sure I have the answer. If you were building locally and you had the image SHA, then you could tag it with name + version, but I'm not familiar enough with docker hub to know how to do that within the website.

**Comment by srbala** [comment]
@metasim Issue no longer valid, please close

**Comment by fzs** [comment]
Version 1.6.2 is outdated. A tagged image for the recent v1.9.0 is available on Docker Hub.
